<?php

/**
 * @return mixed
 */
function reports_menu() {
  // Отчеты
  $items['training-center/reports'] = array(
    'title' => 'Отчеты по дистанционному обучению',
    'page callback' => 'reports_main_page',
    'access arguments' => array('administer training'),
    'type' => MENU_CALLBACK,
  );
  // Отчет по подпискам и завершению курсов за период
  $items['reports/signup'] = array(
    'title' => 'Отчет по подпискам и завершению курсов за период',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('reports_signup_form'),
    'access arguments' => array('administer training'),
    'type' => MENU_CALLBACK,
  );
  // Отчет по подпискам и завершению курсов за период
  $items['reports/stat'] = array(
    'title' => 'Отчет по подпискам и завершению курсов за период',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('reports_stat_form'),
    'access arguments' => array('administer training'),
    'type' => MENU_CALLBACK,
  );
  // Персональная активность
  $items['reports/personal'] = array(
    'title' => 'Отчет по персональной активности в Центре дистанционного обучения',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('reports_personal_form'),
    'access arguments' => array('administer training'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Главная страница отчетов.
 * @return string
 */
function reports_main_page() {

  $items['items'] = array(
    l('Отчет по подпискам и завершению курсов за период', 'reports/signup'),
    l('Статистика прохождения курсов дистанционного обучения', 'reports/stat'),
    l('Отчет по персональной активности в Центре дистанционного обучения', 'reports/personal'),
  );

  return theme('item_list', $items);
}

/**
 * Форма для первого типа отчетности
 * @param $form
 * @param $form_state
 * @return mixed
 */
function reports_signup_form($form, &$form_state) {

  $format = 'Y-m-d';

  if (isset($_GET['start_date'])) {
    $start_date = $_GET['start_date'];
  } else {
    $start_date = time();
  }

  if (isset($_GET['end_date'])) {
    $end_date = $_GET['end_date'];
  } else {
    $end_date = time();
  }

  $form = array();

  $form['start_date'] = array(
    '#type' => 'date_popup',
    // types 'date_text' and 'date_timezone' are also supported. See .inc file.
    '#title' => t('Start date'),
    '#default_value' => date($format, $start_date),
    '#date_format' => $format,
    '#date_label_position' => 'within',
    // See other available attributes and what they do in date_api_elements.inc
    '#date_increment' => 15,
    // Optional, used by the date_select and date_popup elements to increment minutes and seconds.
    '#date_year_range' => '-3:+3',
    // Optional, used to set the year range (back 3 years and forward 3 years is the default).
    '#datepicker_options' => array(),
    // Optional, as of 7.x-2.6+, used to pass in additional parameters from the jQuery Datepicker widget.
  );

  $form['end_date'] = array(
    '#type' => 'date_popup',
    // types 'date_text' and 'date_timezone' are also supported. See .inc file.
    '#title' => t('End date'),
    '#default_value' => date($format, $end_date),
    '#date_format' => $format,
    '#date_label_position' => 'within',
    // See other available attributes and what they do in date_api_elements.inc
    '#date_increment' => 15,
    // Optional, used by the date_select and date_popup elements to increment minutes and seconds.
    '#date_year_range' => '-3:+3',
    // Optional, used to set the year range (back 3 years and forward 3 years is the default).
    '#datepicker_options' => array(),
    // Optional, as of 7.x-2.6+, used to pass in additional parameters from the jQuery Datepicker widget.
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Сформировать отчет'),
  );

  if (isset($_GET['start_date'])) {
    $form['table'] = array(
      '#markup' => reports_signup_output($start_date, $end_date),
    );
  }

  return $form;
}

/**
 * @param $form
 * @param $form_state
 * @return string
 */
function reports_signup_form_submit($form, &$form_state) {
  $start_date = strtotime($form_state['values']['start_date']);
  $end_date = strtotime($form_state['values']['end_date']);

  $form_state['redirect'] = array(
    'reports/signup',
    array(
      'query' => array(
        'start_date' => $start_date,
        'end_date' => $end_date,
      ),
    ),
  );
}

/**
 * Форма для второго типа отчетности.
 * @param $form
 * @param $form_state
 */
function reports_stat_form($form, &$form_state) {
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Сформировать отчет'),
  );

  if (isset($_GET['action'])) {
    $form['table'] = array(
      '#markup' => reports_stat_output(),
    );
  }

  return $form;
}

function reports_stat_form_submit($form, &$form_state) {
  $form_state['redirect'] = array(
    'reports/stat',
    array(
      'query' => array(
        'action' => 'submit',
      ),
    ),
  );
}

/**
 * @param $form
 * @param $form_state
 * @return mixed
 */
function reports_personal_form($form, &$form_state) {
  if (isset($_GET['user'])) {
    $user = $_GET['user'];
  } else {
    $user = '';
  }

  $form['standard']['first-col']['fullname'] = array(
    '#type' => 'textfield',
    '#title' => t('ФИО'),
    '#size' => 100,
    '#default_value' => $user,
    '#autocomplete_path' => 'userbook/autocomplete/fullname',
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Сформировать отчет'),
  );

  if (isset($_GET['user'])) {
    $form['table'] = array(
      '#markup' => reports_personal_output($user),
    );
  }

  return $form;
}

/**
 * @param $form
 * @param $form_state
 */
function reports_personal_form_submit($form, &$form_state) {
  //dpm($form_state);
  $form_state['redirect'] = array(
    'reports/personal',
    array(
      'query' => array(
        'user' => $form_state['values']['fullname'],
      ),
    ),
  );
}

/**
 * Функция формирует отчет для первого типа и выводит его.
 * @param $start_date
 * @param $end_date
 * @return string
 */
function reports_signup_output($start_date, $end_date) {
  $courses = reports_signup_courses($start_date, $end_date);
  if($courses) {
    $first_lessons = reports_first_lessons($courses);
    $result = reports_signup_results($first_lessons, $start_date, $end_date);

    return reports_signup_table($result, $start_date, $end_date);
  } else {
    return '<div id="no-results">Нет результатов за период c ' . date('d.m.Y', $start_date) . ' по ' . date('d.m.Y', $end_date) . '</div>';
  }
}

/**
 * @return string
 */
function reports_stat_output() {
  // Список курсов
  $data = reports_stat_courses();
  // Количество подписавшихся
  reports_stat_signup_count($data);
  // Количество завершенных
  reports_course_evaluate_count($data);

  return reports_stat_table($data);
}

function reports_personal_output($user) {
  $data = reports_personal_courses($user);

  reports_personal_signup($data);

  return reports_personal_table($data);
}

/**
 * Функция возвращает список курсов, на которые подписан пользователь.
 * @param $user
 * @return mixed
 */
function reports_personal_courses($user) {
  $flag_signup = flag_get_flag('signup');

  $query = db_select('field_data_field_user_full_name', 'ufn');
  $query->join('flag_content', 'f', 'ufn.entity_id = f.uid');
  $query->join('field_data_field_course2', 'fc', 'fc.entity_id = f.content_id');
  $query->join('node', 'n', 'n.nid = fc.field_course2_target_id');
  $query->join('field_data_field_block', 'fb', 'fb.entity_id = fc.field_course2_target_id');
  $query->join('node', 'n2', 'fb.field_block_target_id = n2.nid');
  $db_and = db_and();
  $db_and->condition('field_user_full_name_value', $user);
  $db_and->condition('f.fid', $flag_signup->fid);
  $query->condition($db_and);
  $query->distinct();
  $query->addField('n2', 'title', 'block_name');
  $query->addField('n', 'title', 'course_name');
  $query->addField('fc', 'field_course2_target_id', 'course_id');
  $query->addField('f', 'uid', 'uid');
  $result = $query->execute()->fetchAll();

  return $result;
}

/**
 * Функция возвращает время подписки на курс
 * @param $data
 * @return mixed
 */
function reports_personal_signup($data) {
  foreach ($data as $key => $course) {
    $first_lesson = reports_first_lesson($course->course_id);
    $query = db_select('flag_content', 'f')
      ->condition('content_id', $first_lesson)
      ->condition('uid', $course->uid)
      ->fields('f', array('timestamp'))
      ->execute()
      ->fetchField();

    $data[$key]->signup_time = $query;
  }

  return $data;

}

/**
 * Функция получает массив из уникальных id курсов, на которые были подписаны пользователи за указанный период $date - $date2.
 * На выходе массив из id курсов.
 * @param $start_date
 * @param $end_date
 * @return string
 */
function reports_signup_courses($start_date, $end_date) {
  $flag_signup = flag_get_flag('signup');

  $query = db_select('flag_content', 'f');
  $query->join('field_data_field_course2', 'fc', 'f.content_id = fc.entity_id');
  $db_and = db_and();
  $db_and->condition('f.timestamp', array($start_date, $end_date), 'BETWEEN');
  $db_and->condition('f.fid', $flag_signup->fid);
  $query->condition($db_and);
  $query->distinct();
  $query->addField('fc', 'field_course2_target_id', 'course_id');
  $result = $query->execute()->fetchAll();

  if ($result) {
    foreach ($result as $item) {
      $courses[] = $item->course_id;
    }
    return $courses;
  } else {
    return FALSE;
  }
}

/**
 * Функция ищет id первого урока для указанных курсов
 * @param $courses
 * Массив из Id курсов
 * @return string
 */
function reports_first_lessons($courses) {

  foreach ($courses as $course_id) {
    $query = db_select('node', 'n');
    $query->join('field_data_field_course2', 'fc', 'fc.entity_id = n.nid');
    $query->condition('fc.field_course2_target_id', $course_id);
    $query->orderBy('n.title');
    $query->range(0, 1);
    $query->fields('n', array('nid'));
    $lessons[] = $query->execute()->fetchField();
  }

  return $lessons;
}

/**
 * Функция возраващает id первого урока для указанного курса
 * @param $course
 * @return mixed
 */
function reports_first_lesson($course) {

  $query = db_select('node', 'n');
  $query->join('field_data_field_course2', 'fc', 'fc.entity_id = n.nid');
  $query->condition('fc.field_course2_target_id', $course);
  $query->orderBy('n.title');
  $query->range(0, 1);
  $query->fields('n', array('nid'));
  $lesson = $query->execute()->fetchField();

  return $lesson;
}

/**
 * Функция ищет id последнего урока для указанного курса.
 * @param $courses
 * @return array
 */
function reports_last_lesson($course) {

    $query = db_select('node', 'n');
    $query->join('field_data_field_course2', 'fc', 'fc.entity_id = n.nid');
    $query->condition('fc.field_course2_target_id', $course);
    $query->fields('n', array('nid'));
    $count = $query->countQuery()->execute()->fetchField();
    $query->range($count - 1, $count);
    $lesson = $query->execute()->fetchField();

  return $lesson;
}

/**
 * Функция делает выборку по подписанным материалам с условиями.
 * @param $first_lessons
 * @param $start_date
 * @param $end_date
 * @return string
 */
function reports_signup_results($first_lessons, $start_date, $end_date) {
  // Флаг подписки
  $flag_signup = flag_get_flag('signup');

  $query = db_select('flag_content', 'f');
  // Пользователи отметившие
  $query->join('users', 'u', 'f.uid = u.uid');
  // Получаем ФИО
  $query->join('field_data_field_user_full_name', 'ufn', 'ufn.entity_id = u.uid');
  // Должность
  $query->join('field_data_field_user_position', 'up', 'up.entity_id = u.uid');
  // Офис
  $query->join('field_data_field_user_office', 'uo', 'uo.entity_id = u.uid');
  // id курса
  $query->join('field_data_field_course2', 'fc', 'fc.entity_id = f.content_id');
  // Название блока
  $query->join('field_data_field_block', 'fb', 'fb.entity_id = fc.field_course2_target_id');
  $query->join('node', 'nb', 'nb.nid = fb.field_block_target_id');
  // Название курса
  $query->join('node', 'n', 'fc.field_course2_target_id = n.nid');
  // Отдел
  $query->join('field_data_group_audience', 'ga', 'ga.entity_id = u.uid');
  $query->join('og', 'o', 'o.gid = ga.group_audience_gid');
  // Условия
  $db_and = db_and();
  $db_and->condition('f.content_id', $first_lessons, 'IN');
  $db_and->condition('f.fid', $flag_signup->fid);
  $db_and->condition('f.timestamp', array($start_date, $end_date), 'BETWEEN');
  $query->condition($db_and);
  // Поля
  $query->addField('nb', 'title', 'block_name');
  $query->addField('n', 'title', 'course_name');
  $query->addField('fc', 'field_course2_target_id', 'course_id');
  $query->addField('u', 'uid',  'uid');
  $query->addField('ufn', 'field_user_full_name_value', 'fullname');
  $query->addField('up', 'field_user_position_value', 'position');
  $query->addField('o', 'label', 'department');
  $query->addField('uo', 'field_user_office_value', 'office');
  $query->addField('f', 'timestamp', 'signup_time');

  $results = $query->execute()->fetchAll();

  foreach($results as $key => $row) {
    $results[$key]->evaluate = reports_course_evaluate($row->course_id, $row->uid);
  }

  return $results;
}

/**
 * Функция проверяет, завершен ли курс
 * @param $course_id
 * @param $uid
 * @return bool|string
 */
function reports_course_evaluate($course_id, $uid) {
  // Получаем id последнего урока для указанного курса
  $query = db_select('node', 'n');
  $query->join('field_data_field_course2', 'fc', 'fc.entity_id = n.nid');
  $query->condition('fc.field_course2_target_id', $course_id);
  $query->fields('n', array('nid'));
  $count = $query->countQuery()->execute()->fetchField();
  $query->range($count - 1, $count);
  $last_lesson_id = $query->execute()->fetchField();
  // Находим все результаты теста для последнего урока
  $query2 = db_select('node', 'n');
  $query2->join('field_data_field_lesson', 'fl', 'n.nid = fl.field_lesson_target_id');
  $query2->join('node', 'n2', 'fl.entity_id = n2.nid');
  $query2->join('quiz_node_results', 'qnr', 'n2.nid = qnr.nid');
  $query2->condition('n.nid', $last_lesson_id);
  $query2->condition('qnr.uid', $uid);
  $query2->fields('qnr');
  $count2 = $query->countQuery()->execute()->fetchField();
  $query->range($count2 - 1, $count2);
  $quiz_result = $query2->execute()->fetchObject();

  // Если есть результаты
  if ($quiz_result) {
    $quiz_nid = $quiz_result->nid;
    $quiz_vid = $quiz_result->vid;
    // Сдан ли данный тест
    $is_passed_quiz = quiz_is_passed($uid, $quiz_nid, $quiz_vid);
    if($is_passed_quiz == TRUE) {
      return date('d.m.Y', $quiz_result->time_end);
    }
  } else {
    return 'Не завершен';
  }
}

/**
 * Подсчитываем количество подписавшихся.
 * Примечание: можно делать выборку с таблицы flag_counts, но почему то есть расхождения с ней.
 * @param $lesson
 * @return mixed
 */
function reports_stat_signup_count($data) {
  $flag_signup = flag_get_flag('signup');

  foreach ($data as $key => $item) {
    // Получаем id первого урока для данного курса
    $lesson_id = reports_first_lesson($item->course_id);
    // Количество подписавшихся
    $count = 0;

    $query = db_select('flag_content', 'fc')
      ->condition('fc.content_id', $lesson_id)
      ->condition('fc.fid', $flag_signup->fid)
      ->fields('fc')
      ->countQuery()
      ->execute()
      ->fetchField();

    $data[$key]->signup_count = $query;
  }

  return $data;
}

/**
 * Функция вычисляет количество пройденных курсов
 * @param $data
 * @return mixed
 */
function reports_course_evaluate_count($data) {
  foreach ($data as $key => $item) {
    // Получаем id последнего урока для данного курса
    $lesson_id = reports_last_lesson($item->course_id);
    // Количество успешно пройденных курсов
    $count = 0;
    // Получаем все результаты тестов для последнего урока данного курса
    $query = db_select('node', 'n');
    $query->join('field_data_field_lesson', 'fl', 'n.nid = fl.field_lesson_target_id');
    $query->join('quiz_node_results', 'qnr', 'fl.entity_id = qnr.nid');
    $query->condition('n.nid', $lesson_id);
    $query->fields('qnr');
    $quiz_results = $query->execute()->fetchAll();
    // Проверяем каждый результат, сдан ли тест.
    foreach ($quiz_results as $quiz_result) {
      $quiz_nid = $quiz_result->nid;
      $quiz_vid = $quiz_result->vid;
      $uid = $quiz_result->uid;
      // Сдан ли данный тест
      $is_passed_quiz = quiz_is_passed($uid, $quiz_nid, $quiz_vid);
      if($is_passed_quiz == TRUE) {
        $count++;
      }
    }
    // Добавляем информацию к массиву data
    $data[$key]->evaluate_count = $count;
  }

  return $data;
}

/**
 * Функция получает список курсов и блоков
 * @return mixed
 */
function reports_stat_courses() {
  $query = db_select('node', 'n');
  $query->join('field_data_field_block', 'fb', 'n.nid = fb.entity_id');
  $query->join('node', 'n2', 'fb.field_block_target_id = n2.nid');
  $query->addField('n2', 'title', 'block_name');
  $query->addField('n', 'title', 'course_name');
  $query->addField('n', 'nid', 'course_id');
  $query->condition('n.status', 1);
  $courses = $query->execute()->fetchAll();

  return $courses;
}

/**
 * Вывод результатов в табличном виде для первого типа отчета.
 * @param $data
 * @param $start_date
 * @param $end_date
 * @return string
 */
function reports_signup_table($data, $start_date, $end_date) {

  //Дальше создаем таблицу и выводим полученные данные
  // Создаем   заголовок таблицы
  $caption = t('Отчет по подпискам и завершению курсов за период с ' . date('d.m.Y', $start_date) . ' по ' . date('d.m.Y', $end_date));
  // Создаем заголовки столбцов
  $header = array(
    array(
      'data' => t('№'),
    ),
    array(
      'data' => t('Название блока'),
    ),
    array(
      'data' => t('Название курса'),
    ),
    array(
      'data' => t('ФИО пользователя'),
    ),
    array(
      'data' => t('Должность'),
    ),
    array(
      'data' => t('Отдел'),
    ),
    array(
      'data' => t('Офис'),
    ),
    array(
      'data' => t('Дата подписки'),
    ),
    array(
      'data' => t('Дата завершения курса'),
    ),
  );

  foreach ($data as $key => $item) {
    $rows[] = array(
      array(
        'data' => $key + 1,
      ),
      array(
        'data' => $item->block_name,
      ),
      array(
        'data' => $item->course_name,
      ),
      array(
        'data' => $item->fullname,
      ),
      array(
        'data' => $item->position,
      ),
      array(
        'data' => $item->department,
      ),
      array(
        'data' => $item->office,
      ),
      array(
        'data' => date('d.m.Y', $item->signup_time),
      ),
      array(
        'data' => $item->evaluate,
      ),
    );
  }

  //dpm($rows);

  $output = theme('table', array(
      // Шапка таблицы
      'header' => $header,
      // Тело таблицы
      'rows' => $rows,
      // Заголовок таблицы
      'caption' => $caption,
      // Атрибуты таблицы
      'attributes' => array('width' => '100%'),
    )
  );

  //reports_export_stuff($header, $rows);

  return $output;
}

/**
 * Вывод результатов в табличном виде для второго типа отчета.
 * @param $data
 * @param $start_date
 * @param $end_date
 * @return string
 */
function reports_stat_table($data) {

  //Дальше создаем таблицу и выводим полученные данные
  // Создаем   заголовок таблицы
  $caption = t('Статистика прохождения курсов дистанционного обучения');
  // Создаем заголовки столбцов
  $header = array(
    array(
      'data' => t('№'),
    ),
    array(
      'data' => t('Название блока'),
    ),
    array(
      'data' => t('Название курса'),
    ),
    array(
      'data' => t('Количество подписей'),
    ),
    array(
      'data' => t('Количество успешного прохождения курса'),
    ),
  );

  foreach ($data as $key => $item) {
    $rows[] = array(
      array(
        'data' => $key + 1,
      ),
      array(
        'data' => $item->block_name,
      ),
      array(
        'data' => $item->course_name,
      ),
      array(
        'data' => $item->signup_count,
      ),
      array(
        'data' => $item->evaluate_count,
      ),
    );
  }

  //dpm($rows);

  $output = theme('table', array(
      // Шапка таблицы
      'header' => $header,
      // Тело таблицы
      'rows' => $rows,
      // Заголовок таблицы
      'caption' => $caption,
      // Атрибуты таблицы
      'attributes' => array('width' => '100%'),
    )
  );

  //reports_export_stuff($header, $rows);

  return $output;
}

function reports_personal_table($data) {

  //Дальше создаем таблицу и выводим полученные данные
  // Создаем   заголовок таблицы
  $caption = t('Статистика прохождения курсов дистанционного обучения');
  // Создаем заголовки столбцов
  $header = array(
    array(
      'data' => t('№'),
    ),
    array(
      'data' => t('Название блока'),
    ),
    array(
      'data' => t('Название курса'),
    ),
    array(
      'data' => t('Дата подписки'),
    ),
    array(
      'data' => t('Дата успешного прохождения курса'),
    ),
    array(
      'data' => t('Общее количество тестов (уроков)'),
    ),
    array(
      'data' => t('Количество попыток сдачи тестов'),
    ),
  );

  foreach ($data as $key => $item) {
    $rows[] = array(
      array(
        'data' => $key + 1,
      ),
      array(
        'data' => $item->block_name,
      ),
      array(
        'data' => $item->course_name,
      ),
      array(
        'data' => date('d.m.Y', $item->signup_time),
      ),
      array(
        'data' => '',
      ),
    );
  }

  //dpm($rows);

  $output = theme('table', array(
      // Шапка таблицы
      'header' => $header,
      // Тело таблицы
      'rows' => $rows,
      // Заголовок таблицы
      'caption' => $caption,
      // Атрибуты таблицы
      'attributes' => array('width' => '100%'),
    )
  );

  //reports_export_stuff($header, $rows);

  return $output;
}

// Экспорт в excel
function reports_export_stuff($headers2, $data2) {

  foreach ($headers2 as $header) {
    $headers['stat'][] = $header['data'];
  }

  foreach ($data2 as $key => $data3) {
    foreach ($data3 as $data4) {
      //dpm($data4);
      $data['stat'][$key][] = $data4['data'];
    }
  }


  //$data['stat'] = '';
  //dpm($result);
  module_load_include('inc', 'phpexcel');



  // Store the file in sites/default/files
  $dir = file_stream_wrapper_get_instance_by_uri('public://')->realpath();
  $filename = 'export.xlsx';
  $path = "$dir/$filename";

  // Use the .xls format
  $options = array('format' => 'xlsx', 'title' => 'sdfdgfdg');


  $result = phpexcel_export($headers, $data, $path, $options);
  if ($result == PHPEXCEL_SUCCESS) {
    drupal_set_message(t("We did it !"));
    //return $path;
  }
  else {
    drupal_set_message(t("Oops ! An error occured !"), 'error');
  }
}
